# Generated by Django 6.0.5 on 2026-05-23 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('speciality', models.CharField(choices=[('General', 'General Physician'), ('Cardiology', 'Cardiology (Dil)'), ('Neurology', 'Neurology (Dimagh)'), ('Orthopedics', 'Orthopedics (Haddi)'), ('Pediatrics', 'Pediatrics (Bacha)'), ('Gynecology', 'Gynecology (Khawateen)'), ('Dermatology', 'Dermatology (Jild)'), ('ENT', 'ENT (Kaan Naak Gala)'), ('Ophthalmology', 'Ophthalmology (Aankh)'), ('Dentistry', 'Dentistry (Daant)')], max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('fee', models.DecimalField(decimal_places=2, max_digits=8)),
                ('available', models.BooleanField(default=True)),
                ('joined', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
